apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 4
  template:
    spec:
      containers:
        - name: my-nginx
          image: nginx:latest
          env:
            - name: CUSTOM_ENV_VARIABLE
              value: DEV_abc123
