apiVersion: apps/v1
kind: Deployment
metadata:
  name: karpenter
spec:
  selector:
    matchLabels:
      run: karpenter
  replicas: 2
  template:
    metadata:
      labels:
        run: karpenter
    spec:
      containers:
        - name: karpenter
          image: XXX
